In [1]:
import numpy as np
from scipy import signal

In [2]:
x1 = np.ones((3,3))
x2 = np.ones((2,2))
out = signal.convolve(x1, x2, mode = 'same') 
print(out)

[[1. 2. 2.]
 [2. 4. 4.]
 [2. 4. 4.]]


In [1]:
import autograd
import numpy as npo
from scipy.signal import convolve as sp_convolve
R = lambda *x: npo.random.randint(0,5, size=x)
npo.random.seed(32)
from importlib import reload

In [2]:
reload(autograd)
from autograd.scipy.signal import convolve as ag_convolve

In [7]:
A_35 = R(3, 5)
A_34 = R(3, 4)
A_342 = R(3, 4, 2)
A_2543 = R(2, 5, 4, 3)
A_24232 = R(2, 4, 2, 3, 2)

for mode in ["same"]:
    if not npo.allclose(
        ag_convolve(A_35, A_34, axes=([1], [0]), mode=mode)[1, 2],
        sp_convolve(A_35[1, :], A_34[:, 2], mode),
    ):
        first = ag_convolve(A_35, A_34, axes=([1], [0]), mode=mode)
        second = sp_convolve(A_35[1, :], A_34[:, 2], mode)
        print(f"first({first.shape}): {first}")
        print(f"second({second.shape}) {second}")
    assert npo.allclose(
        ag_convolve(A_35, A_34, axes=([1], [0]), mode=mode)[1, 2],
        sp_convolve(A_35[1, :], A_34[:, 2], mode),
    )
    assert npo.allclose(
        ag_convolve(A_35, A_34, axes=([], []), dot_axes=([0], [0]), mode=mode),
        npo.tensordot(A_35, A_34, axes=([0], [0])),
    )
    assert npo.allclose(
        ag_convolve(A_35, A_342, axes=([1], [2]), dot_axes=([0], [0]), mode=mode)[2],
        sum([sp_convolve(A_35[i, :], A_342[i, 2, :], mode) for i in range(3)]),
    )
    assert npo.allclose(
        ag_convolve(A_2543, A_24232, axes=([1, 2], [2, 4]), dot_axes=([0, 3], [0, 3]), mode=mode)[2],
        sum(
            [
                sum(
                    [sp_convolve(A_2543[i, :, :, j], A_24232[i, 2, :, j, :], mode) for i in range(2)]
                )
                for j in range(3)
            ]
        ),
    )


    # assert npo.allclose(
    #     ag_convolve(A_35, A_34, axes=([], []), dot_axes=([0], [0]), mode=mode),
    #     npo.tensordot(A_35, A_34, axes=([0], [0])),
    # )
    # assert npo.allclose(
    #     ag_convolve(A_35, A_342, axes=([1], [2]), dot_axes=([0], [0]), mode=mode)[2],
    #     sum([sp_convolve(A_35[i, :], A_342[i, 2, :], mode) for i in range(3)]),
    # )   


wrong order
A ((3, 5)) = [[2 1 3 0 3]
 [1 1 0 0 0]
 [0 0 3 1 0]] and 
B ((3, 4))= [[3 3 2 3]
 [1 1 0 2]
 [1 4 3 1]]
A ((3, 4)) = [[3 3 2 3]
 [1 1 0 2]
 [1 4 3 1]] and 
B ((3, 7))= [[0 2 1 3 0 3 0]
 [0 1 1 0 0 0 0]
 [0 0 0 3 1 0 0]]
combining (3, 3, 5) and (3, 4) with axes [[1], [0]]
A_axnums((3, 3, 5)): [0, 5, 2], B_axnums((3, 4)): [5, 4], return shape: (3, 5, 4)
wrong order
A ((3, 5)) = [[2 1 3 0 3]
 [1 1 0 0 0]
 [0 0 3 1 0]] and 
B ((3, 4))= [[3 3 2 3]
 [1 1 0 2]
 [1 4 3 1]]
A ((3, 4)) = [[3 3 2 3]
 [1 1 0 2]
 [1 4 3 1]] and 
B ((3, 7))= [[0 2 1 3 0 3 0]
 [0 1 1 0 0 0 0]
 [0 0 0 3 1 0 0]]
combining (3, 3, 5) and (3, 4) with axes [[1], [0]]
A_axnums((3, 3, 5)): [0, 5, 2], B_axnums((3, 4)): [5, 4], return shape: (3, 5, 4)
A ((3, 5)) = [[2 1 3 0 3]
 [1 1 0 0 0]
 [0 0 3 1 0]] and 
B ((3, 4))= [[3 3 2 3]
 [1 1 0 2]
 [1 4 3 1]]
A ((3, 4)) = [[3 3 2 3]
 [1 1 0 2]
 [1 4 3 1]] and 
B ((3, 5))= [[2 1 3 0 3]
 [1 1 0 0 0]
 [0 0 3 1 0]]
combining (3, 5) and (3, 4) with axes [[0], [0]]
A_axnums((3

In [6]:
A_35 = R(3, 5)
A_34 = R(3, 4)
A_342 = R(3, 4, 2)
A_2543 = R(2, 5, 4, 3)
A_24232 = R(2, 4, 2, 3, 2)

for mode in ["valid"]:
    if not npo.allclose(
        ag_convolve(A_35, A_34, axes=([1], [0]), mode=mode)[1, 2],
        sp_convolve(A_35[1, :], A_34[:, 2], mode),
    ):
    # first = ag_convolve(A_35, A_34, axes=([1], [0]), mode=mode)
    # second = sp_convolve(A_35[1, :], A_34[:, 2], mode)
    # print(f"first({first.shape}): {first}")
    # print(f"second({second.shape}) {second}")


    # assert npo.allclose(
    #     ag_convolve(A_35, A_34, axes=([], []), dot_axes=([0], [0]), mode=mode),
    #     npo.tensordot(A_35, A_34, axes=([0], [0])),
    # )
    # assert npo.allclose(
    #     ag_convolve(A_35, A_342, axes=([1], [2]), dot_axes=([0], [0]), mode=mode)[2],
    #     sum([sp_convolve(A_35[i, :], A_342[i, 2, :], mode) for i in range(3)]),
    # )   


wrong order
A ((3, 4)) = [[1 0 0 2]
 [1 4 1 4]
 [0 1 4 4]] and 
B ((3, 5))= [[4 4 4 1 0]
 [2 1 2 2 2]
 [0 4 2 2 4]]
A ((3, 4)) = [[1 0 0 2]
 [1 4 1 4]
 [0 1 4 4]] and 
B ((3, 5))= [[4 4 4 1 0]
 [2 1 2 2 2]
 [0 4 2 2 4]]
combining (3, 4) and (3, 3, 3) with axes [[0], [1]]
A_axnums((3, 4)): [5, 1], B_axnums((3, 3, 3)): [2, 5, 4], return shape: (4, 3, 3)
first((3, 4, 3)): [[[ 8  5  1]
  [20 20  8]
  [20 20 17]
  [40 34 20]]

 [[ 3  4  4]
  [ 6  9 10]
  [ 9  6 10]
  [16 16 20]]

 [[ 6  4  6]
  [16 12 10]
  [ 4 18 10]
  [20 28 24]]]
second((3,)) [ 9  6 10]


In [19]:
A_35 = R(3, 5)
A_24 = R(2, 4)
A_342 = R(3, 4, 2)
A_2543 = R(2, 5, 4, 3)
A_24232 = R(2, 4, 2, 3, 2)

for mode in ["valid"]:
    # first = ag_convolve(A_35, A_34, axes=([1], [0]), mode=mode)
    # second = sp_convolve(A_35[1, :], A_34[:, 2], mode)
    # print(f"first({first.shape}): {first}")
    # print(f"first[1,2]: {first[1, 2]}")
    # print(f"second {second}")

    first = ag_convolve(A_24, A_35, axes=([0], [1]), mode=mode)
    second = sp_convolve(A_24[:, 2], A_35[1, :], mode)
    print(f"first({first.shape}): {first}")
    print(f"first[1,2]: {first[2,1]}")
    print(f"second {second}")

    # assert npo.allclose(
    #     ag_convolve(A_35, A_34, axes=([], []), dot_axes=([0], [0]), mode=mode),
    #     npo.tensordot(A_35, A_34, axes=([0], [0])),
    # )
    # assert npo.allclose(
    #     ag_convolve(A_35, A_342, axes=([1], [2]), dot_axes=([0], [0]), mode=mode)[2],
    #     sum([sp_convolve(A_35[i, :], A_342[i, 2, :], mode) for i in range(3)]),
    # )   


A ((2, 4)) = [[2 3 0 2]
 [1 2 4 4]] and 
B ((3, 5))= [[2 1 3 0 2]
 [4 0 3 2 2]
 [3 1 2 0 2]]
A ((2, 4)) = [[2 3 0 2]
 [1 2 4 4]] and 
B ((3, 5))= [[2 1 3 0 2]
 [4 0 3 2 2]
 [3 1 2 0 2]]
combining (2, 4) and (3, 2, 4) with axes [[0], [1]]
A_axnums((2, 4)): [5, 1], B_axnums((3, 2, 4)): [2, 5, 4], return shape: (4, 3, 4)
first((4, 3, 4)): [[[ 4  7  3  4]
  [ 4  6  7  6]
  [ 5  5  2  4]]

 [[ 7 11  6  6]
  [ 8  9 12 10]
  [ 9  8  4  6]]

 [[ 8  4 12  0]
  [16  0 12  8]
  [12  4  8  0]]

 [[10 10 12  4]
  [16  6 16 12]
  [14  8  8  4]]]
first[1,2]: [16  0 12  8]
second [16  0 12  8]


In [3]:
A_35 = R(3, 5)
A_24 = R(2, 4)
A_342 = R(3, 4, 2)
A_2543 = R(2, 5, 4, 3)
A_24232 = R(2, 4, 2, 3, 2)

for mode in ["same"]:
    # first = ag_convolve(A_35, A_34, axes=([1], [0]), mode=mode)
    # second = sp_convolve(A_35[1, :], A_34[:, 2], mode)
    # print(f"first({first.shape}): {first}")
    # print(f"first[1,2]: {first[1, 2]}")
    # print(f"second {second}")

    first = ag_convolve(A_24, A_35, axes=([0], [1]), mode=mode)
    second = sp_convolve(A_24[:, 2], A_35[1, :], mode)
    print(f"first({first.shape}): {first}")
    print(f"first[1,2]: {first[2,1]}")
    print(f"second {second}")

    # assert npo.allclose(
    #     ag_convolve(A_35, A_34, axes=([], []), dot_axes=([0], [0]), mode=mode),
    #     npo.tensordot(A_35, A_34, axes=([0], [0])),
    # )
    # assert npo.allclose(
    #     ag_convolve(A_35, A_342, axes=([1], [2]), dot_axes=([0], [0]), mode=mode)[2],
    #     sum([sp_convolve(A_35[i, :], A_342[i, 2, :], mode) for i in range(3)]),
    # )   


A ((2, 4)) = [[3 0 2 2]
 [2 4 2 4]] and 
B ((3, 5))= [[3 4 0 3 4]
 [1 3 2 1 4]
 [3 1 3 1 2]]
A ((3, 5)) = [[3 4 0 3 4]
 [1 3 2 1 4]
 [3 1 3 1 2]] and 
B ((6, 4))= [[0 0 0 0]
 [0 0 0 0]
 [3 0 2 2]
 [2 4 2 4]
 [0 0 0 0]
 [0 0 0 0]]
combining (5, 4, 2) and (3, 5) with axes [[0], [1]]
A_axnums((5, 4, 2)): [5, 1, 2], B_axnums((3, 5)): [3, 5], return shape: (4, 2, 3)
first((4, 3, 2)): [[[ 8  9]
  [12  7]
  [11  9]]

 [[16  0]
  [12  8]
  [ 4 12]]

 [[ 8  6]
  [10  6]
  [ 8  8]]

 [[16  6]
  [16 10]
  [10 14]]]
first[1,2]: [10  6]
second [10  6]


In [5]:
a = npo.zeros((3,4))
b= npo.zeros((3,3,3))
out = npo.einsum(a, [5, 1], b, [2, 5, 4])
print(out.shape)

(4, 3, 3)


In [6]:
A_35 = R(3, 5)
A_34 = R(3, 4)
A_342 = R(3, 4, 2)
A_2543 = R(2, 5, 4, 3)
A_24232 = R(2, 4, 2, 3, 2)

for mode in ["valid"]:
    first = ag_convolve(A_34, A_35, axes=([0], [1]), mode=mode)
    second = sp_convolve(A_34[:, 2], A_35[1, :], mode)
    print(f"first({first.shape}): {first}")
    print(f"second {second}")


    # assert npo.allclose(
    #     ag_convolve(A_35, A_34, axes=([], []), dot_axes=([0], [0]), mode=mode),
    #     npo.tensordot(A_35, A_34, axes=([0], [0])),
    # )
    # assert npo.allclose(
    #     ag_convolve(A_35, A_342, axes=([1], [2]), dot_axes=([0], [0]), mode=mode)[2],
    #     sum([sp_convolve(A_35[i, :], A_342[i, 2, :], mode) for i in range(3)]),
    # )   


A ((3, 4)) = [[0 2 2 3]
 [4 1 4 1]
 [2 4 3 4]] and 
B ((3, 5))= [[0 4 3 1 4]
 [2 0 0 1 3]
 [3 4 0 0 2]]
A ((3, 4)) = [[0 2 2 3]
 [4 1 4 1]
 [2 4 3 4]] and 
B ((3, 5))= [[0 4 3 1 4]
 [2 0 0 1 3]
 [3 4 0 0 2]]
combining (3, 4) and (3, 3, 3) with axes [[0], [1]]
A_axnums((3, 4)): [5, 1], B_axnums((3, 3, 3)): [2, 5, 4], return shape: (4, 3, 3)
first((4, 3, 3)): [[[16 20 10]
  [ 4  0  4]
  [22  8  0]]

 [[10 21 21]
  [ 8  2  7]
  [16 16  4]]

 [[22 26 21]
  [ 6  2 10]
  [25 12  4]]

 [[13 22 25]
  [ 8  3 10]
  [16 16  6]]]
second [ 6  2 10]
